DROP TABLE additionalfields CASCADE;
DROP TABLE applications CASCADE;
DROP TABLE applicationstatuses CASCADE;
DROP TABLE departments CASCADE;
DROP TABLE educationalbackgrounds CASCADE;
DROP TABLE materials CASCADE;
DROP TABLE programs CASCADE;
DROP TABLE users CASCADE;
DROP SEQUENCE hibernate_sequence CASCADE;